---
- name: Upgrade BIG-IP software
  hosts: lb
  connection: local
  gather_facts: False

  vars:
    provider:
      password: "{{ ansible_ssh_pass }}"
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      validate_certs: False


  tasks:

    - name: Query BIG-IP facts
      bigip_device_facts:
        gather_subset:
         - virtual-servers
        provider: "{{provider}}"
      register: bigip_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: bigip_facts
    - local_action:
        module: copy
        content: "{{ bigip_facts.virtual_servers | to_nice_json }}"
        dest: output-virtual-servers-outputs.yml