---
- name: Classic APP Delete Imperative model
  hosts: localhost
  connection: local
  gather_facts: false


  vars:
    bigipmgmt1: "192.168.86.50"
    bigipmgmt1: "192.168.86.46"
    user: "admin"
    password: "W3lcome098!"

  tasks:
    - name: Delete AS3 DC1
      uri:
        url: "https://192.168.86.50:443/mgmt/shared/appsvcs/declare/{{ partition }}"
        method: DELETE
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{user}}"
        password: "{{password}}"
        validate_certs: false
      delegate_to: localhost

    - name: Delete AS3 DC2
      uri:
        url: "https://192.168.86.46:443/mgmt/shared/appsvcs/declare/{{ partition }}"
        method: DELETE
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{user}}"
        password: "{{password}}"
        validate_certs: false
      delegate_to: localhost
