---
- name: Classic APP Deployment Declarative model
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Device Information
    bigipmgmt1: "192.168.86.50"
    bigipmgmt2: "192.168.86.46"
    user: "admin"
    password: "W3lcome098!"
    app_name: "{{app_name}}"

    # Application Information
    partition: "{{partition_name}}"
    appAS3tempalte: as3_basic.json
    apps:
      - name: "{{app_name}}"
        vsip: "{{vip}}"
        vsport: 80
        memberport: 80
        poolname: "{{app_name}}"
        members:
          - 10.1.20.11
          - 10.1.20.12
          - 10.1.20.13


  tasks:
    - name: CREATE AS3 JSON BODY
      set_fact:
        as3_app_body: "{{ lookup('template', 'templates//{{ appAS3tempalte }}', split_lines=False) }}"

  
    - name: PUSH AS3 DC1 
      uri:
        url: "https://{{bigipmgmt1}}:443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template', 'templates/{{ appAS3tempalte }}') }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{user}}"
        password: "{{password}}"
        validate_certs: false
      delegate_to: localhost
      
 
    - name: PUSH AS3 DC2
      uri:
        url: "https://{{bigipmgmt2}}:443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template', 'templates/{{ appAS3tempalte }}') }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{user}}"
        password: "{{password}}"
        validate_certs: false
      delegate_to: localhost
