#Rotate F5 Credentials

---
- name: "Rotate F5 Credentials"
  hosts: f5
  gather_facts: false
  connection: local
  vars_files:
    variables.yaml

  vars:
    provider:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: 443
      validate_certs: false

  tasks:
    
    - name: Task 4 - Get current time on BIG-IP
      command: date "+20%y%m"
      register: date

    - name: Update Admin Password
      bigip_user:
        state: present
        username_credential: admin
        password_credential: NewSecretPassword
        provider: "{{provider}}"
      loop: "{{ devices }}"
      delegate_to: localhost

    - name: Update Root Password
      bigip_user:
        state: present
        username_credential: root
        password_credential: NewSecretPassword
        provider: "{{provider}}"
      loop: "{{ devices }}"
      delegate_to: localhost
      